config/routes.rb
Rails.application.routes.draw do
  root 'surveys#new'
  get 'welcome/index'

  resources :surveys, only: [:index, :new, :create, :show] do
    resources :questions, only: [:new, :create]
    resources :submissions, only: [:new, :create, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer, presence: true
  belongs_to :submission
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, presence: true
  belongs_to :survey
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
end

app/models/survey.rb
class Survey < ApplicationRecord
  validates :name, presence: true
  has_many :submissions, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions
  accepts_nested_attributes_for :questions

  def has_questions?
    questions.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_survey

  def new
    @questions = @survey.questions
    @question = @survey.questions.build
  end

  def create
    @question = @survey.questions.build(question_params)
    if @question.save
      redirect_to new_survey_question_path(@survey)
    else
      render :new 
    end
  end

  private
    def get_survey
      @survey = Survey.find(params[:survey_id])
    end
    
    def question_params
      params.require(:question).permit(:question, :survey_id)
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new 
    @submission = survey.submissions.build
    survey.questions.each do |question|
      @submission.answers.build(question_id: question.id)
    end
  end
  # TODO: Test Driven Design  = WRITE TESTS

  def create
    @submission = survey.submissions.build(submission_params)
    if @submission.save
      redirect_to survey_submission_path(survey, @submission)
    else 
      render :new
    end
  end

  def show
    survey
    @submission = Submission.find(params[:id])
  end

  private
    def survey 
      @survey ||= Survey.find(params[:survey_id])
    end

    def submission_params
      params.require(:submission).permit(:survey_id, answers_attributes: [:question_id, :answer])
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to new_survey_question_path(@survey)
    else
      render :new #// better way to show errors
    end
  end

  def show
   @survey = Survey.find(params[:id])
  end

  private
    def survey_params
      params.require(:survey).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyCraft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_svelte' %>
  </head>

  <body>
    <div class='container mx-auto'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/new.html.erb
<div class='space-y-8'>
  <h1 class='block text-5xl'>Survey: <%= @survey.name %></h1>
  <div class='block'><%= link_to "Go to Survey", survey_path(@survey), class: "bg-gray-500 rounded-full py-3 px-6" %></div>

  <% if !@survey.has_questions? %>
    <p class='block'>This survey needs questions!!!</p>

  <% else %>
    <ol class='block'>
      <% @survey.questions.each do |question| %>
        <% if question.id %>
          <li><%= question.question %>?</li>
        <% end %>
      <% end %>
    </ol>
  <% end %>

  <%= form_with(model: [@survey, @question]) do |f| %>
    <div class='space-y-4'>
      <div class='block'><%= f.label :question, 'What question do you want to ask?' %></div>
      <div class='block'><%= f.text_field :question, class: 'border-b-2' %></div>
      <% if @question.errors.any? %>
        <% @question.errors.full_messages.each do |message| %>
          <div class='block text-red-500'><%= message %></div>
        <% end %>
      <% end %>

      <div class='block'><%= f.submit('Add Question', { class: 'bg-indigo-500 rounded-full py-3 px-6' }) %></div>
    </div>
  <% end %>
</div>

app/views/submissions/new.html.erb
<div class='space-y-8'>
  <h1 class='block text-5xl'>Survey: <%= @survey.name %></h1>
  <% if !@survey.has_questions? %>
    <p class='block text-2xl'>This survey needs questions!!!</p>

  <% else %>
    <%= form_with model: @submission, url: survey_submissions_path(@survey) do |submission_form| %>
        <div class='space-y-4'>
          <%= submission_form.fields_for :answers, @submission.answers do |answer_form| %>
            <div class='block text-xl'><%= answer_form.hidden_field(:question_id) %></div>
            <div class='block text-xl'><%= answer_form.label :question, answer_form.object.question.question %>?</div>
            <div class='block text-3xl'><%= answer_form.text_field(:answer, class: 'border-b-2') %></div>
          <% end %>

          <% if @submission.errors.any? %>
            <ul>
              <% @submission.errors.each do |error| %>
                <li class='text-red-500'><%= error.full_message %></li>
              <% end %>
            </ul>
          <% end %>
          <div><%= submission_form.submit('Submit', { class: 'bg-indigo-500 rounded-full py-3 px-6' }) %></div>
        </div>

    <% end %>
  <% end %>

</div>

app/views/submissions/show.html.erb
<div class='space-y-8'>
  <h1 class='block text-5xl'>Survey: <%= @survey.name %></h1>

  <div class='space-y-4'>
    <% @submission.answers.each do |answer| %>
      <div class='block text-xl'><%= answer.question.question %>?</div>
      <div class='block text-3xl'><%= answer.answer %></div>
    <% end %>
  </div>

  <div>
    <%= link_to "See all Surveys", surveys_path, class: "bg-indigo-500 rounded-full py-3 px-6" =%>
  </div>
</div>

app/views/surveys/index.html.erb
<div class='space-y-8'>
  <h1 class='block text-5xl'>SurveyCraft</h1>
  <% @surveys.each do |survey| %>
    <div class='block'><%= link_to survey.name, survey_path(survey), class: "bg-gray-500 rounded-full py-3 px-6" %></div>
  <% end %>
  <div class='block'><%= link_to "New", new_survey_path, class: "bg-indigo-500 rounded-full py-3 px-6" %></div>
</div>

app/views/surveys/new.html.erb
<h1 class='block text-5xl'>Let's Create a New Survey</h1>
<% if @survey.errors.any? %>
  <ul>
    <% @survey.errors.each do |error| %>
      <li>
        <%= error.full_message %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_for @survey do | f | %>
  <div class='space-y-4'>
    <div class='block'><%= f.label :name %></div>
    <div class='block'><%= f.text_field(:name, class: 'border-b-2') %></div>
    <div class='block'><%= f.submit('Submit', { class: 'bg-indigo-500 rounded-full py-3 px-6' }) %></div>
  </div>
<% end %>

app/views/surveys/show.html.erb
<h1 class='block text-5xl'>Survey: <%= @survey.name %></h1>
<div class='space-y-4'>
  <% if !@survey.has_questions? %>
    <p class='block text-2xl'>This survey needs questions!!!</p>
    <div>
      <%= link_to "Add Questions to Survey", new_survey_question_path(@survey), class: "bg-indigo-500 rounded-full py-3 px-6" =%>
    </div>

  <% else %>
      <% @survey.questions.each do |question| %>
        <div class='block text-2xl'><%= question.question %>?</div>
      <% end %>
      <div>
        <%= link_to "Start Survey", new_survey_submission_path(@survey), class: "bg-indigo-500 rounded-full py-3 px-6" =%>
      </div>
  <% end %>


</div>

app/views/welcome/index.html.erb
<%#had to turn this off as it is used in application.html.erb yield%>
<%#<h1>Welcome#index</h1>%>
<%#<p>Find me in app/views/welcome/index.html.erb</p>%>